### ISSUE TITLE
POMDPModels

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPOMDP/POMCPOW.jl#14]
Hey @zsunberg ! Why does "POMDPModels" fall under the `extras` category in the Project.toml file rather than the `deps` section?

**Comment by zsunberg** [comment]
POMDPModels is only used for testing - the POMCPOW code itself does not depend on POMDPModels.

**Comment by logankilpatrick** [comment]
Ah, got it :) thanks! 

Best, 
Logan Kilpatrick
