### ISSUE TITLE
Slow Timekeeping

### ISSUE THREAD

**Issue by WhiffleFish** [JuliaPOMDP/POMCPOW.jl#29]
`CPUtime_us()` can be extremely expensive

![image](https://user-images.githubusercontent.com/52610169/141663694-14d64e1b-1924-453c-8115-699c7bb9aebc.png)
The lower-rightmost block in an `action` call profile here is ALL `CPUtime_us()` calls ^

According to my benchmarks...
each `CPUtime_us()` call on average takes about `1.195 μs ± 152.206 ns`
each `time()` call on average takes about `16.687 ns ±  1.789 ns` which is ~71x faster

```julia
solver = POMCPOWSolver(tree_queries=100_000,
                     eps=0.01,
                     criterion=MaxUCB(10.0),
                     enable_action_pw=true,
                     check_repeat_obs=false,
                     alpha_observation=1/8,
                     rng=MersenneTwister(2))

problem = LightDark1D()
policy = POMCPOWPlanner(solver, problem)
ib = initialstate(problem)
@benchmark action(policy, ib)
```

The resulting times to produce an action are:
Using `CPUtime_us()` : `334.407 ms ±  18.087 ms`
Using `time()` : `196.712 ms ±  16.637 ms`

So, I don't know how attached we are to CPUTime but purely by changing our timekeeping method to base julia we seem to get on average a 1.7x speed improvement.

If we're not terribly attached to CPUTime I can quickly submit a PR making the appropriate time-keeping changes that result in the 1.7x speed improvement.

**Comment by zsunberg** [comment]
We should have a `time` or `timer` keyword argument to the solver with a default of either `time = ()->1e-6*CPUtime_us()` or `time = time` or `time = ()->1e-9*time_ns()`. Not sure what the advantages or disadvantages are, and it may be highly platform dependent. I wonder how cputime could be so slow.

**Comment by zsunberg** [comment]
Seems like time_ns might be best
