### ISSUE TITLE
Unintuitive/incorrect criteria rule

### ISSUE THREAD

**Issue by acshi** [JuliaPOMDP/POMCPOW.jl#30]
In `select_best` in `criteria.jl`, the first rule `if n == 0 && ltn <= 0.0` does not make sense to me.

If a given child action has not been explored AND the parent has been explored only once (ignoring the possibility of heuristic n values less than 1), THEN use the default initialization value for this child action... WHY? I had been expecting that any unexplored child would be prioritized here, but in order to get `criterion_value == Inf` for prioritization the parent needs to have both MORE than 1 trial (`ltn > 0.0`) so that the third case gets executed with `ltn / n` giving `Inf`. The middle case seems pointless, since if `init_V == -Inf` and so `tree.v[node] == -Inf` then the value will ALWAYS be that because POMCPOW only ever modifies the value with `tree.v[best_node] += (R - tree.v[best_node]) / tree.n[best_node]`... Perhaps that is for some other very specific use?

```
ltn = log(tree.total_n[h])
for node in tree.tried[h]
    n = tree.n[node]
    if n == 0 && ltn <= 0.0
        criterion_value = tree.v[node]
    elseif n == 0 && tree.v[node] == -Inf
        criterion_value = Inf
    else
        criterion_value = tree.v[node] + crit.c * sqrt(ltn / n)
    end
...
end
```

What is going on here?

**Comment by zsunberg** [comment]
Yeah, that code is not very readable/understandable. I think the reason for the middle case was that if you have -Inf + Inf, you get NaN, so I needed to fill something in there. But it might be better to make it -Inf. Sorry I don't have a better memory. If you'd like to change it, please make sure there is a test that exercises that line.

**Comment by acshi** [comment]
Okay so the middle case makes sense then.

The main concern I have is the first condition, because since the default initialization value is generally 0, then if you have two child nodes, this code will explore the first child node _twice_ before exploring the second child node.

First time exploring the parent
child 0: criterion_value = Inf
child 1: criterion_value = Inf
And say we choose child 0, and it gets a rollout value of 10

Second time exploring the parent:
child 0: criterion_value = 10 + some UCB value
child 1: criterion_value = 0
So we choose child 0 to explore a second time, although most UCB algorithms would explore the new child.

Third time exploring the parent:
child 0: criterion_value = 10 + some UCB value
child 1: criterion_value = Inf
So now we finally get the new child prioritized!! But why wait the extra trial?

So, is this the expected behavior? Or is this maybe a bug? I really can't tell if this was intentional or not for some reason!

**Comment by zsunberg** [comment]
Hmm... yeah, I think you might be right. I agree it seems like the second
time should have child 1: criterion_value = Inf

But, if we changed it to ltn < 0.0, then in the third branch we would end
up with 0.0/0 = NaN. What do you think the correct solution should be?

Also, I think you should embrace the clarity of one-based indexing instead
of saying "child 0" :)

2017 Zach apologizes again for the really hard-to-understand code - he
didn't know that other people would actually use it.

**Comment by zsunberg** [comment]
One option would be to look at the trees with D3Tree(action_info(planner,
b)[2][:tree]) and see if you see it exploring the same node twice.
